services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11l"
      DISK_SIZE: "32G"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      USERNAME: "Lenovo"
      PASSWORD: "130236Qa"
      LANGUAGE: "Chinese"
      REGION: "zh-CN"
      KEYBOARD: "zh-CN"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
